spring.datasource.url=jdbc:postgresql://dpg-d8trnprsq97s73cgj7lg-a:5432/money_tracker_db_7n9k
spring.datasource.username=money_tracker_db_7n9k_user
spring.datasource.password=AqmGCjgn20JQk2yfk013xey3SQctNQ80

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

server.port=${PORT:8080}
